name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - run: npm install --no-save @testmo/testmo-cli
    - run: |
          if [[ -z "${TESTMO_URL}" ]]; then
            echo "The TESTMO_URL secret is not defined for this repository"
            exit 1
          fi

          if [[ -z "${TESTMO_TOKEN}" ]]; then
            echo "The TESTMO_TOKEN secret is not defined for this repository"
            exit 1
          fi
      env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
    - run: |
          testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "UI test run" \
            --source "unui-tests" \
            --results results/*.xml \
      env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
